version: '3.3'
services:
  social-api:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: social-api-cont
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env